### ISSUE TITLE
[FW] landing overshot

### ISSUE THREAD

**Issue by svpcom** [PX4/PX4-Autopilot#15668]
**Describe the bug**
In 1.11 and current master FW overshot when landing

**To Reproduce**
1.  ```
     export PX4_HOME_LAT=55.721693 PX4_HOME_LON=37.919516 PX4_HOME_ALT=160
     make px4_sitl gazebo_plane
     ```
2. Uploaded mission 
[test_mission.plan.txt](https://github.com/PX4/Firmware/files/5160954/test_mission.plan.txt)

3. Run mission
4. Get overshot 375m

**Expected behavior**
In 1.10.1 no overshot detected

**Log Files and Screenshots**
Normal land (1.10.1):
![normal_land 1.10.1](https://user-images.githubusercontent.com/503830/91957185-5e8f5c00-ed0e-11ea-85dd-0b7c78628f1a.png)
Overshot land (1.11 and master):
![overshot_land 1.11 and master](https://user-images.githubusercontent.com/503830/91957192-6222e300-ed0e-11ea-8f02-005df67e140e.png)

**Comment by Jaeyoung-Lim** [comment]
@svpcom I think this is related to the flaps being deployed, so the plane never lands

**Comment by svpcom** [comment]
@Jaeyoung-Lim It seems problem is deeper. For example if I do
```
commander takeoff
<delay until takeoff>
commander land
```
In 1.10.1 it land successfully with pitch 8 degrees. In 1.11 and master - it descend with pitch 20 degrees and crash

**Comment by ryanjAA** [comment]
Here is a flightiest from Monday on 1.11 RC3 with auto takeoff and auto land and flaps enabled. Worked fine (disregard wind, it was ~25+ mph during the Pixhawk 1 testing).

Pixhawk 1:
https://review.px4.io/plot_app?log=b3cd9471-7917-4ee2-8ae9-82e3fce0c7f7

Pixhawk 4:
https://review.px4.io/plot_app?log=f6d0e25a-68e9-4148-aa08-d108c5cf3f92

**Comment by ryanjAA** [comment]
Just checked. Works on pix 4. Not pix 1.

**Comment by svpcom** [comment]
SITL logs: https://logs.px4.io/plot_app?log=cc984641-2af5-49be-8720-7d47314931a4

**Comment by svpcom** [comment]
@dagar I've found root of problem, but unable to explain how it works. First or all I've found that current master has this problem fixed. Doing git bisect i've found that it fixed in commit 67a0e1993a76faaea265a32d0f8620450531f5f4. Minimal valueable subset of this commit (that fix overshot issue) applied to release-1.11 branch is:
``` .diff
diff --git a/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp b/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
index 1109b82e6a..e608d2dcf4 100644
--- a/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
+++ b/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
@@ -1539,7 +1539,7 @@ FixedwingPositionControl::Run()
                _alt_reset_counter = _local_pos.vz_reset_counter;
                _pos_reset_counter = _local_pos.vxy_reset_counter;
 
-               airspeed_poll();
+               //airspeed_poll();
                _manual_control_setpoint_sub.update(&_manual_control_setpoint);
                _pos_sp_triplet_sub.update(&_pos_sp_triplet);
                vehicle_attitude_poll();
```
But call of `airspeed_poll` is in code from 2017 when all worked fine

**Comment by ryanjAA** [comment]
So I tried this today on 1.11.2 and on Master and it is still present when using Gazebo. But when using FlightGear and JSBsim it works fine, no overshoot.

I dont understand the change made in https://github.com/PX4/PX4-Autopilot/commit/67a0e1993a76faaea265a32d0f8620450531f5f4 but maybe the FDM has something to do with it in the other simulators and why it works in real life but not gazebo.

It should however be fixed to work with Gazebo.

**Comment by Jaeyoung-Lim** [comment]
@ryanjAA I still think it is related to the flaps being deployed in Gazebo... would you be able to test in gazebo with the flaps disabled?

**Comment by ryanjAA** [comment]
@Jaeyoung-Lim You're correct. It is the flaps. Does not overshoot in 1.11.2 or Master at https://github.com/PX4/PX4-Autopilot/commit/1cd36d4c8c928dd506c4deca56f517e5e0267f24 Interestingly, on 1.11.2 the performance on landing is quite different but neither overshoot.

https://logs.px4.io/plot_app?log=ea5dd011-01d8-4475-ab82-341fdb779c8b
https://logs.px4.io/plot_app?log=547a3826-d9d0-4446-a923-f6b136c30293

![Screenshot from 2020-12-08 11-21-28](https://user-images.githubusercontent.com/31726584/101518480-95958f00-3947-11eb-89b2-a0d4ce980575.png)

**Comment by svpcom** [comment]
@Jaeyoung-Lim How to disable flaps in sitl-gazebo?

**Comment by mrpollo** [comment]
Thanks for the fix @Jaeyoung-Lim

**Comment by ryanjAA** [comment]
@svpcom set FW_FLAPS_LND_SCL to 0.
