### ISSUE TITLE
[Bug] SF45B lidar with not working CONFIG_DRIVERS_DISTANCE_SENSOR_LIGHTWARE_SF45_SERIAL

### ISSUE THREAD

**Issue by Mahmood-Hussain** [PX4/PX4-Autopilot#25099]
### Describe the bug

I build a custom firmware with additional configuration CONFIG_DRIVERS_DISTANCE_SENSOR_LIGHTWARE_SF45_SERIAL=1 after flashing the firmware to FC it I cannot see the OBSTACLE_DISTANCE

### To Reproduce

1. set `CONFIG_DRIVERS_DISTANCE_SENSOR_LIGHTWARE_SF45_SERIAL=1` in PX4-Autopilot/boards/cubepilot/cubeorangeplus/default.px4board
2. Build firmware `make cubepilot_cubeorangeplus`
3. Connect sf45b lidar to TELEM2
4. Connect lidar with micro usb to lighware studio and set baud rate to 921600 as suggested in https://docs.px4.io/main/en/sensor/sf45_rotating_lidar.html
5. Set `SENS_EN_SF45_CFG` to `TELEM2`
6. In analyze tools check OBSTACLE_DISTANCE message (there is nothing)
7. `lightware_sf45_serial status`
`lightware_sf45_serial: read: 0 events, 0us elapsed, 0.00us avg, min 0us max 0us 0.000us rms
lightware_sf45_serial: com_err: 0 events`

### Expected behavior

After setup I should be able to see the obstacle overlay map

### Screenshot / Media

![Image](https://github.com/user-attachments/assets/26984aac-10df-4e64-b7f8-c2ff4176cc46)

### Flight Log

nsh> dmesg -f
al] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: payload length invalid, restarting data request
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: payload length invalid, restarting data request
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: payload length invalid, restarting data request
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
INFO  [cdcacm_autostart] Starting mavlink on /dev/ttyACM0 (SYS_USB_AUTO=2)
INFO  [mavlink] mode: Onboard, data rate: 100000 B/s on /dev/ttyACM0 @ 2000000B
uavcan_mag adding channel for topic sensor_mag node 125...
uavcan_mag channel 125 instance 1 ok
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
INFO  [lightware_sf45_serial] INFO: start of packet not valid
ERROR [parameters] get: param 65535 invalid
WARN  [health_and_arming_checks] Preflight Fail: Avoidance system not ready
INFO  [vehicle_magnetometer] MAG switch from #0 -> #1
WARN  [health_and_arming_checks] Preflight Fail: Avoidance system not ready
uavcan_gnss adding channel for topic sensor_gps node 125...
uavcan_gnss node 125 instance 0 ok
uavcan_gnss node 125 topic sensor_gps instance 0 ok
WARN  [health_and_arming_checks] Preflight: GPS fix too low
WARN  [health_and_arming_checks] Preflight Fail: Avoidance system not ready
WARN  [uavcan] GNSS Fix2 msg detected for ch 0; disabling Fix msg for this node
INFO  [mavlink] Starting mavlink shell

### Software Version

PX4: 1.15.4

### Flight controller

CubeOrangePlus

### Vehicle type

None

### How are the different components wired up (including port information)

SF45B --> TELEM2

### Additional context

I checked it with ardupilot and it works, I can see the radar obstacle map in mission planner. 
Tried this:
nsh> lightware_sf45_serial status
lightware_sf45_serial: read: 0 events, 0us elapsed, 0.00us avg, min 0us max 0us 0.000us rms
lightware_sf45_serial: com_err: 0 events
nsh> lightware_sf45_serial status
lightware_sf45_serial: read: 0 events, 0us elapsed, 0.00us avg, min 0us max 0us 0.000us rms
lightware_sf45_serial: com_err: 0 events

I also tried with mavlink using companion computer but that too didn't work however I was able to see the OBSTACLE_DISTANCE MESSAGE in that case and there was overlay issue which I raised here https://github.com/mavlink/qgroundcontrol/issues/13074 that setup also worked with Ardupilot and MissionPlanner.

**Comment by dirksavage88** [comment]
@Mahmood-Hussain there were issues in 1.15.4 with starting up the sf45 on some boards or specific uarts on the board (have since been resolved in 1.16.x). I believe the fmuv5x had similar issues with startup. You can try the release candidate and see if it comes up. 

See: https://github.com/PX4/PX4-Autopilot/pull/23565

**Comment by Mahmood-Hussain** [comment]
Thank you @dirksavage88 for your reply. I tried PX4 v1.16.0 but still no luck let me share the logs
```
NuttShell (NSH) NuttX-11.0.0
nsh> dmesg -f
ch: CUBEPILOT_CUBEORANGEPLUS
PX4 git-hash: 2e6fd9dd729e927169c95be9e0df3194db1d9459
PX4 version: 1.16.0 c0 (17825984)
PX4 git-branch: main
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: 886acbbdb4f061e5c0ce1a76afbcfa7cb7df9849
Build datetime: Jun 24 2025 08:53:18
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 10.2.1 20201103 (release)
PX4GUID: 0006000000003338383930325106002b002b
MCU: STM32H7[4|5]xxx, rev. V
ERROR [bsondump] open '/fs/mtd_caldata' failed (2)
New /fs/mtd_caldata size is:
ERROR [bsondump] open '/fs/mtd_caldata' failed (2)
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 786 bytes, decoded 786 bytes (INT32:20, FLOAT:17)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
Loading airframe: /etc/init.d/airframes/4001_quad_x
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 128528 bytes
Board sensors: /etc/init.d/rc.board_sensors
ms5611 #0 on SPI bus 4
icm45686 #0 on SPI bus 4 rotation 10
icm45686 #1 on SPI bus 4 rotation 6
icm45686 #2 on SPI bus 1 rotation 3
ak09916 #0 on I2C bus 4 address 0xC rotation 13
ms5611 #1 on SPI bus 1
ekf2 [624:237]
INFO  [px4io] IO FW CRC match
Board mavlink: /etc/init.d/rc.board_mavlink
INFO  [mavlink] mode: Minimal, data rate: 2880 B/s on /dev/ttyS4 @ 57600B
Starting Lightware SF45 Rangefinder (serial) on /dev/ttyS1
Starting Main GPS on /dev/ttyS2
Starting MAVLink on /dev/ttyS0
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS0 @ 57600B
INFO  [cdcacm_autostart] Starting CDC/ACM autostart
INFO  [logger] logger started (mode=all)
INFO  [uavcan] Node ID 1, bitrate 1000000

NuttShell (NSH) NuttX-11.0.0
nsh> sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
INFO  [cdcacm_autostart] Starting mavlink on /dev/ttyACM0 (SYS_USB_AUTO=2)
INFO  [mavlink] mode: Onboard, data rate: 100000 B/s on /dev/ttyACM0 @ 2000000B
WARN  [health_and_arming_checks] Preflight Fail: Accel 0 uncalibrated
WARN  [health_and_arming_checks] Preflight Fail: Compass 0 uncalibrated
uavcan_mag adding channel for topic sensor_mag node 125...
uavcan_mag channel 125 instance 1 ok
INFO  [vehicle_magnetometer] MAG switch from #0 -> #1
ERROR [lightware_sf45_serial] serial write fail -1
WARN  [health_and_arming_checks] Preflight Fail: Accel 0 uncalibrated
WARN  [health_and_arming_checks] Preflight Fail: Compass 1 uncalibrated
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
uavcan_gnss adding channel for topic sensor_gps node 125...
uavcan_gnss node 125 instance 0 ok
uavcan_gnss node 125 topic sensor_gps instance 0 ok
WARN  [uavcan] GNSS Fix2 msg detected for ch 0; disabling Fix msg for this node
WARN  [health_and_arming_checks] Preflight Fail: Accel 0 uncalibrated
WARN  [health_and_arming_checks] Preflight: GPS fix too low
WARN  [health_and_arming_checks] Preflight Fail: Compass 1 uncalibrated
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
INFO  [mavlink] Setting system clock from SYSTEM_TIME sent by 255/190
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
```

I will also try to debug why is it unhappy, maybe hardware needs some time (delay). I don't see lidar getting power and it's not rotating.

**Comment by dirksavage88** [comment]
How are you powering the lidar? It should rotate as soon as it receives data. If it is not rotating, it's not getting any data at all (even if you send mavlink on that uart by mistake, it will start rotating...)

After you reflashed did you set the params for the SF45 on that telem port and disable mavlink streams on that same telem  (if enabled)?

**Comment by Mahmood-Hussain** [comment]
I am connecting through TELEM 2 and power source is the same. 
[Here are my params](https://github.com/user-attachments/files/20916006/px4_16.0.x_sf45b_direct.txt)

As I mentioned earlier the same hardware setup works with Ardupilot and MissionPlanner. 

![Image](https://github.com/user-attachments/assets/012aabee-2f1c-4162-95b9-f88f1bbe529c)

**Comment by dirksavage88** [comment]
@Mahmood-Hussain that is fine, however the px4 telem port and uart configuration will likely differ from ardupilot. I do not have a cube orange plus to test, but you can try on a different telemetry port and at a lower baud rate perhaps. 

```
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
ERROR [lightware_sf45_serial] serial write fail 5
```

This error plus the fact that the lidar is NOT spinning is very indicative of data not getting to the sf45. PX4 and ardupilot also recommend the lidar be powered by a voltage regulator and not the telem port.

**Comment by dirksavage88** [comment]
fixed in https://github.com/PX4/PX4-Autopilot/pull/25399
